apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "echo hello hatim; sleep 5;"]
    env:
    - name: myname
      value: hatim loha
