apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  restartPolicy: Never
  containers:
  - name: c00
    image: ubuntu
    command: ["echo", "hatim loha"]
  - name: c01
    image: ubuntu
    command: ["echo", "hatim loha"]
