apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-namespace

---

apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins-namespace
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins
    ports:
    - containerPort: 8080
    - containerPort: 50000
